- name: update configuration file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: update alert configuration file
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/prometheus/{{ item }}
  loop: "{{ alert_files }}"

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: prometheus service status
  ansible.builtin.shell: netstat -lntp | grep 9090

- name: update alert manager configuration file
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: alert manager status check
  ansible.builtin.shell: netstat -lntp | grep 9093
