- name: update configuration file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: update alert configuration file
  ansible.builtin.template:
    src: {{ item }}
    dest: /opt/prometheus/{{ item }}
  loop: "{{ alert_files }}"

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

